import { useEffect, useMemo, useState } from 'react';
import { AppShell, type View } from './layouts/AppShell';
import { DistributionChart, TelemetryChart, Verdict } from './components/Visualizations';
import { assessmentService } from './services/assessmentService';
import { ApiError } from './adapters/pythonAssessmentAdapter';
import type { Assessment, ComponentRecord, UploadMetadata } from './types/assessment';

type Stage = 'login' | 'home' | 'processing' | 'report' | 'app';
const profiles = [{name:'EOS-08', scenario:'Payload Subsystem Screening'}, {name:'Gaganyaan', scenario:'Avionics Tier-1 Screening'}];
const procedure = ['Loading mission telemetry…','Validating telemetry…','Running dynamic anomaly screening…','Running 168h drift analysis…','Compiling screening assessment…'];
const fmt = (value: number) => value.toLocaleString('en-IN');

export default function App() {
  const [stage, setStage] = useState<Stage>('login'); const [view, setView] = useState<View>('home'); const [assessment, setAssessment] = useState<Assessment | null>(null); const [profile, setProfile] = useState('EOS-08'); const [progress, setProgress] = useState(0); const [selectedId, setSelectedId] = useState('ISRO_IC_00003'); const [upload, setUpload] = useState<UploadMetadata | null>(null); const [uploadFile, setUploadFile] = useState<File | null>(null); const [error, setError] = useState('');
  const selected = assessment?.components.find(c => c.id === selectedId) ?? assessment?.components[0];
  const selectComponent = async (componentId: string) => { setSelectedId(componentId); try { const component = await assessmentService.getComponent(componentId); setAssessment(current => current ? {...current, components: current.components.map(item => item.id === componentId ? component : item)} : current); } catch { /* Current assessment already provides the selected component evidence. */ } };
  const run = async (fromUpload = false) => { setError(''); setStage('processing'); setProgress(0); for (let i=1;i<=5;i++) { await new Promise(r=>setTimeout(r, 520)); setProgress(i); } try { const result = fromUpload && uploadFile ? await assessmentService.runUploadedAssessment(uploadFile) : await assessmentService.runMissionAssessment(profile); setAssessment(result); setSelectedId(result.components.find(c=>c.finalSystemReject)?.id ?? result.components[0].id); setStage('report'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Assessment processing failed. The telemetry was not changed.'); setStage('home'); } };
  const handleFile = async (file?: File) => { if (!file) return; setUploadFile(file); setError(''); try { const metadata = await assessmentService.validateUpload(file); setUpload(metadata); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Telemetry validation could not be completed.'; const apiError = caught instanceof ApiError ? caught : undefined; setUpload({name:file.name,size:file.size,rows:0,valid:false,error:message,errorCode:apiError?.code,missingColumns:apiError?.missingColumns,row:apiError?.row,column:apiError?.column}); } };
  if (stage === 'login') return <Login onSignIn={() => setStage('home')}/>;
  if (stage === 'processing') return <Processing progress={progress}/>;
  if (stage === 'report' && assessment) return <Report assessment={assessment} onOpen={() => {setStage('app');setView('overview');}}/>;
  return <AppShell view={view} onView={setView}><div className="workspace">{error && <div className="error-banner">{error}</div>}{stage === 'home' && <Home profile={profile} setProfile={setProfile} upload={upload} onFile={handleFile} onRun={() => run(false)} onUploadRun={() => run(true)}/>} {stage === 'app' && assessment && <Analysis view={view} assessment={assessment} selected={selected} setSelectedId={selectComponent} setView={setView}/>}</div></AppShell>;
}

function Login({onSignIn}:{onSignIn:()=>void}) { return <div className="login"><div className="login-grid"/><section className="login-copy"><div className="brand login-brand"><span className="brand-mark">A</span><span>ABSS<small>AUTOMATED BURN-IN SCREENING SYSTEM</small></span></div><p className="eyebrow">AUTHORIZED ENGINEERING ACCESS</p><h1>COMPONENT SCREENING<br/><em>FOR MISSION READINESS</em></h1><p className="intro">AI-assisted anomaly detection and degradation assessment across controlled burn-in telemetry.</p><div className="system-readiness">{['SCREENING ENGINE','TELEMETRY INTERFACE','ASSESSMENT SERVICES'].map(x=><div key={x}><span className="status-dot"/>{x}<b>READY</b></div>)}</div></section><section className="login-form"><p className="eyebrow">ENGINEERING CREDENTIALS</p><h2>Sign in to ABSS</h2><label>Operator ID<input defaultValue="OPR-ISRO-041"/></label><label>Password<input type="password" defaultValue="missionready"/></label><button className="primary full" onClick={onSignIn}>SIGN IN <span>→</span></button><p className="form-note">Demo engineering access · Credentials are not persisted</p></section><footer>ABSS v1.0 · SCREENING ENVIRONMENT · ACCESS CONTROLLED</footer></div> }

function Home({profile,setProfile,upload,onFile,onRun,onUploadRun}:{profile:string;setProfile:(p:string)=>void;upload:UploadMetadata|null;onFile:(f?:File)=>void;onRun:()=>void;onUploadRun:()=>void}) { const invalid = upload && !upload.valid; return <><div className="page-heading"><div><span className="eyebrow">OPERATIONS / NEW SCREENING</span><h1>COMPONENT SCREENING<br/><em>FOR MISSION READINESS</em></h1><p>AI-assisted anomaly detection and degradation assessment across burn-in telemetry.</p></div><div className="operational-stamp"><span className="status-dot"/>ABSS SERVICES READY<br/><small>ASSESSMENT ENVIRONMENT / NOMINAL</small></div></div><div className="action-grid"><section className="action-panel"><div className="panel-index">01</div><span className="eyebrow">TELEMETRY INTAKE</span><h2>IMPORT ATE DATA</h2><p>Analyze an existing burn-in telemetry dataset through the ABSS screening procedure.</p><div className="upload-schema"><b>REQUIRED CSV COLUMNS</b><code>Component_ID, Lot_ID, Iddq_0h_uA, Iddq_24h_uA</code><small>Example: IC-001, LOT_ALPHA, 10.200, 10.760</small></div><label className={`drop-zone ${upload?.valid ? 'valid':invalid ? 'invalid':''}`}><input type="file" accept=".csv,text/csv" onChange={e=>onFile(e.target.files?.[0])}/>{invalid ? <div className="invalid-upload"><strong>INVALID ATE DATASET</strong><span>{upload.error}</span>{upload.missingColumns?.length ? <code>MISSING: {upload.missingColumns.join(' · ')}</code> : null}{upload.row ? <code>CSV ROW: {upload.row}{upload.column ? ` · COLUMN: ${upload.column}` : ''}</code> : null}<em>CHOOSE ANOTHER FILE</em></div> : <><strong>{upload?.name ?? 'DROP ATE CSV HERE'}</strong><span>{upload ? `${fmt(upload.rows)} component records validated · ${(upload.size/1024).toFixed(1)} KB` : 'or browse files · CSV telemetry only'}</span></>}</label><button className="secondary" disabled={!upload?.valid} onClick={onUploadRun}>RUN MISSION ASSESSMENT <span>→</span></button></section><section className="action-panel mission"><div className="panel-index">02</div><span className="eyebrow">CONTROLLED ASSESSMENT</span><h2>RUN MISSION ASSESSMENT</h2><p>Process mission assessment telemetry through the complete ABSS screening pipeline.</p><div className="profile-list">{profiles.map(p=><button key={p.name} className={profile===p.name?'selected':''} onClick={()=>setProfile(p.name)}><span>{p.name === 'EOS-08' ? 'EO' : 'GA'}</span><div><b>{p.name}</b><small>{p.scenario}</small></div><i>{profile===p.name?'●':'○'}</i></button>)}</div><div className="dataset-note"><b>MISSION PROFILE:</b> {profile.toUpperCase()}<br/><b>DATASET:</b> MISSION ASSESSMENT DATASET</div><button className="primary" onClick={onRun}>RUN MISSION ASSESSMENT <span>→</span></button></section></div><div className="future-profiles"><span>FUTURE SCREENING PROFILES</span>{['CHANDRAYAAN-3','ADITYA-L1','CARTOSAT','RISAT'].map(x=><b key={x}>{x}<small>PLANNED</small></b>)}</div></> }

function Processing({progress}:{progress:number}) { return <div className="processing"><div className="processing-head"><span className="eyebrow">ABSS / ACTIVE PROCEDURE</span><h1>MISSION ASSESSMENT<br/><em>IN PROGRESS</em></h1><p>Assessment services are processing the selected telemetry under the approved screening procedure.</p></div><div className="procedure">{procedure.map((item,i)=><div className={i<progress?'done':i===progress?'running':''} key={item}><span>{i<progress?'✓':i===progress?'◉':'○'}</span><b>{item}</b><small>{i<progress?'COMPLETE':i===progress?'IN PROGRESS':'PENDING'}</small></div>)}</div><div className="progress-line"><i style={{width:`${progress*20}%`}}/></div><p className="processing-foot">DO NOT CLOSE THIS ENGINEERING SESSION DURING ASSESSMENT</p></div> }

function Report({assessment,onOpen}:{assessment:Assessment;onOpen:()=>void}) { const a=assessment.components; const qualified=a.filter(x=>x.verdict==='QUALIFIED').length; const ma=a.filter(x=>x.moduleA!=='PASS').length; const mb=a.filter(x=>x.moduleB==='REJECT').length; return <div className="report"><div className="report-top"><div><span className="eyebrow">MISSION ASSESSMENT REPORT</span><h1>SCREENING ASSESSMENT<br/><em>COMPLETE</em></h1><p>{assessment.assessedAt} · RUN {assessment.id} · {assessment.source === 'LIVE' ? 'LIVE PIPELINE' : 'OFFLINE DEMO MODE'}</p></div><div className="complete-mark"><span>✓</span>ASSESSMENT STATUS<br/><b>COMPLETE</b></div></div><div className="report-meta"><div><small>MISSION PROFILE</small><b>{assessment.mission}</b><span>{assessment.scenario}</span></div><div><small>DATASET</small><b>{assessment.dataset}</b><span>{assessment.source === 'LIVE' ? 'Live Python pipeline result' : 'Offline mock assessment fallback'}</span></div><div><small>FINAL ASSESSMENT</small><b>REVIEW REQUIRED</b><span>Exceptions require engineering disposition</span></div></div><div className="report-metrics"><Metric n={a.length} label="TOTAL COMPONENTS SCREENED"/><Metric n={qualified} label="QUALIFIED COMPONENTS" kind="good"/><Metric n={ma} label="MODULE A ANOMALIES" kind="warn"/><Metric n={mb} label="MODULE B EARLY DRIFT REJECTIONS" kind="bad"/></div><div className="module-completion"><div><span>MODULE A</span><b>Dynamic Anomaly Screening</b><Verdict value="COMPLETE"/></div><div><span>MODULE B</span><b>168h Drift Assessment</b><Verdict value="COMPLETE"/></div></div><button className="primary open" onClick={onOpen}>OPEN MISSION OVERVIEW <span>→</span></button></div> }
function Metric({n,label,kind='' }:{n:number;label:string;kind?:string}) { return <div className={`metric ${kind}`}><b>{fmt(n)}</b><span>{label}</span></div> }

function Analysis({view,assessment,selected,setSelectedId,setView}:{view:View;assessment:Assessment;selected?:ComponentRecord;setSelectedId:(id:string)=>void;setView:(v:View)=>void}) { if (!selected) return null; const titles:Record<View,string>={home:'NEW SCREENING',overview:'MISSION OVERVIEW',component:'COMPONENT INVESTIGATION',lot:'LOT ANALYSIS',register:'SCREENING REGISTER',reports:'ASSESSMENT REPORTS'}; return <><div className="analysis-heading"><div><span className="eyebrow">ANALYSIS / {titles[view]}</span><h1>{titles[view]}</h1><p>{assessment.mission} · {assessment.scenario} · {assessment.id}</p></div><button className="quiet" onClick={()=>setView('home')}>+ NEW SCREENING</button></div>{view==='overview'&&<Overview assessment={assessment} selected={selected} go={setView} pick={setSelectedId}/>} {view==='component'&&<ComponentInvestigation assessment={assessment} component={selected} pick={setSelectedId}/>} {view==='lot'&&<LotAnalysis assessment={assessment} component={selected} pick={setSelectedId}/>} {view==='register'&&<Register assessment={assessment} pick={setSelectedId} go={setView}/>} {view==='reports'&&<Reports assessment={assessment} go={setView}/>}</> }

function Overview({assessment,selected,go,pick}:{assessment:Assessment;selected:ComponentRecord;go:(v:View)=>void;pick:(x:string)=>void}) { const a=assessment.components; const q=a.filter(x=>x.verdict==='QUALIFIED').length; const alerts=a.filter(x=>x.verdict!=='QUALIFIED').slice(0,4); return <><div className="kpi-row"><Metric n={a.length} label="SCREENED"/><Metric n={q} label="QUALIFIED" kind="good"/><Metric n={a.filter(x=>x.moduleA!=='PASS').length} label="MODULE A FLAGS" kind="warn"/><Metric n={a.filter(x=>x.moduleB==='REJECT').length} label="DRIFT REJECTS" kind="bad"/></div><div className="overview-grid"><section className="panel chart-panel"><PanelTitle title="TELEMETRY PRIORITY COMPONENT" action="INVESTIGATE" onClick={()=>go('component')}/><div className="component-strip"><b>{selected.id}</b><span>{selected.lot}</span><Verdict value={selected.verdict}/></div><TelemetryChart component={selected}/></section><section className="panel priority"><PanelTitle title="PRIORITY COMPONENTS" action="OPEN REGISTER" onClick={()=>go('register')}/>{alerts.map(c=><button key={c.id} onClick={()=>{pick(c.id);go('component')}}><span><b>{c.id}</b><small>{c.lot} · Dₘ {c.mahalanobis.toFixed(2)}</small></span><Verdict value={c.verdict}/></button>)}</section></div><section className="panel lot-summary"><PanelTitle title="LOT-LEVEL ANOMALY SUMMARY" action="LOT ANALYSIS" onClick={()=>go('lot')}/><div className="lot-grid">{assessment.lots.map(l=><button key={l.id} onClick={()=>go('lot')}><b>{l.id.replace('LOT_','')}</b><span>{l.population} parts</span><strong>{l.anomalies} <small>FLAGS</small></strong><i style={{width:`${Math.min(100,l.anomalies*2)}%`}}/></button>)}</div></section></> }
function PanelTitle({title,action,onClick}:{title:string;action:string;onClick:()=>void}) { return <div className="panel-title"><b>{title}</b><button onClick={onClick}>{action} →</button></div> }

function ComponentInvestigation({assessment,component,pick}:{assessment:Assessment;component:ComponentRecord;pick:(x:string)=>void}) { const lot=assessment.lots.find(l=>l.id===component.lot)!; const telemetry=[['0H',component.iddq0],['24H',component.iddq24],['96H',component.iddq96],['168H FORECAST',component.moduleBEvaluated?component.forecast168:undefined]]; const prediction=component.moduleBEvaluated&&component.forecast168!==undefined?`${component.forecast168.toFixed(3)} µA`:'NOT EVALUATED'; const slope=component.moduleBEvaluated&&component.slope!==undefined?`${component.slope.toFixed(4)} µA/hr`:'NOT EVALUATED'; return <div className="investigation"><div className="select-component"><label>SELECT COMPONENT<select value={component.id} onChange={e=>pick(e.target.value)}>{assessment.components.map(c=><option key={c.id}>{c.id}</option>)}</select></label><div><span>LOT</span><b>{component.lot}</b></div><Verdict value={component.verdict}/></div><div className="investigate-grid"><section className="panel evidence"><PanelTitle title="BURN-IN TELEMETRY & FORECAST" action="LOT CONTEXT" onClick={()=>{}}/><TelemetryChart component={component}/><div className="telemetry-values">{telemetry.map(([x,y])=><div key={String(x)}><span>{x}</span><b>{typeof y==='number'?`${y.toFixed(3)} µA`:'NOT EVALUATED'}</b></div>)}</div></section><section className="panel flag-why"><span className="eyebrow">ENGINEERING TRACEABILITY</span><h2>WHY WAS THIS COMPONENT FLAGGED?</h2><Verdict value={component.verdict}/><p>{component.reason}</p><div className="reason-line"><b>MODULE B</b>{component.moduleBReason}</div></section></div><div className="details-grid"><section className="panel"><PanelTitle title="MODULE A / DYNAMIC ANOMALY SCREENING" action="COMPLETE" onClick={()=>{}}/><Detail label="PAT STATUS" value={component.patViolated?'VIOLATED':'WITHIN DYNAMIC BOUNDS'} alert={component.patViolated}/><Detail label="LOT MEDIAN" value={`${lot.median.toFixed(3)} µA`}/><Detail label="DYNAMIC PAT BOUNDS" value={`${lot.lowerPat.toFixed(3)} — ${lot.upperPat.toFixed(3)} µA`}/><Detail label="MAHALANOBIS DISTANCE" value={`Dₘ ${component.mahalanobis.toFixed(2)}`} alert={component.mahalanobis>3.03}/><Detail label="COVARIANCE STATUS" value={component.covarianceViolated?'ANOMALY DETECTED':'NOMINAL'} alert={component.covarianceViolated}/></section><section className="panel"><PanelTitle title="MODULE B / 168H DRIFT ASSESSMENT" action="COMPLETE" onClick={()=>{}}/><Detail label="MODULE B STATUS" value={component.moduleB}/><Detail label="168H PREDICTION" value={prediction}/><Detail label="PROJECTED SLOPE" value={slope} alert={Boolean(component.slope&&component.slope>.04)}/><Detail label="EARLY REJECTION" value={component.moduleBEvaluated?(component.moduleB==='REJECT'?'MANDATED':'NOT REQUIRED'):'NOT APPLICABLE'} alert={component.moduleB==='REJECT'}/><Detail label="THRESHOLD" value="0.0400 µA/hr"/></section></div></div> }
function Detail({label,value,alert=false}:{label:string;value:string;alert?:boolean}) { return <div className="detail"><span>{label}</span><b className={alert?'alert':''}>{value}</b></div> }

function LotAnalysis({assessment,component,pick}:{assessment:Assessment;component:ComponentRecord;pick:(x:string)=>void}) { const [lotId,setLotId]=useState(component.lot); const [liveLot,setLiveLot]=useState(assessment.lots.find(l=>l.id===component.lot)!); useEffect(()=>{ assessmentService.getLot(lotId).then(setLiveLot).catch(()=>setLiveLot(assessment.lots.find(l=>l.id===lotId)!)); },[lotId,assessment]); const lot=liveLot; const candidates=assessment.components.filter(c=>c.lot===lotId); const current=candidates.find(c=>c.id===component.id)??candidates[0]; return <><div className="lot-controls"><label>SELECT LOT<select value={lotId} onChange={e=>setLotId(e.target.value)}>{assessment.lots.map(l=><option key={l.id}>{l.id}</option>)}</select></label><label>REFERENCE COMPONENT<select value={current.id} onChange={e=>pick(e.target.value)}>{candidates.map(c=><option key={c.id}>{c.id}</option>)}</select></label></div><div className="lot-metrics"><Metric n={lot.population} label="LOT POPULATION"/><div className="metric"><b>{lot.median.toFixed(2)} <small>µA</small></b><span>LOT MEDIAN</span></div><div className="metric"><b>{lot.robustSigma.toFixed(2)} <small>µA</small></b><span>ROBUST SIGMA</span></div><Metric n={lot.anomalies} label="ANOMALY POPULATION" kind="warn"/></div><section className="panel distribution-panel"><PanelTitle title={`${lotId} / DISTRIBUTION AND DYNAMIC PAT ENVELOPE`} action="AEC-Q001 ADAPTIVE PAT" onClick={()=>{}}/><DistributionChart lot={lot} component={current}/></section><div className="details-grid"><section className="panel"><PanelTitle title="DYNAMIC LIMITS" action="LOT HEALTH" onClick={()=>{}}/><Detail label="LOWER PAT BOUND" value={`${lot.lowerPat.toFixed(3)} µA`}/><Detail label="UPPER PAT BOUND" value={`${lot.upperPat.toFixed(3)} µA`}/><Detail label="SELECTED COMPONENT" value={`${current.id} · ${current.iddq0.toFixed(3)} µA`} alert={current.patViolated}/></section><section className="panel"><PanelTitle title="POPULATION INTERPRETATION" action="ENGINEERING CONTEXT" onClick={()=>{}}/><p className="panel-copy">The selected component is positioned relative to a robust lot-specific distribution. Dynamic PAT bounds are derived from the lot median and IQR-based robust sigma rather than a static global ceiling.</p></section></div></> }

function Register({assessment,pick,go}:{assessment:Assessment;pick:(x:string)=>void;go:(v:View)=>void}) { const [query,setQuery]=useState(''); const [lot,setLot]=useState('ALL'); const [verdict,setVerdict]=useState('ALL'); const rows=useMemo(()=>assessment.components.filter(c=>(lot==='ALL'||c.lot===lot)&&(verdict==='ALL'||c.verdict===verdict)&&c.id.toLowerCase().includes(query.toLowerCase())),[assessment,lot,verdict,query]); return <section className="panel register"><div className="register-tools"><input placeholder="Search component ID" value={query} onChange={e=>setQuery(e.target.value)}/><select value={lot} onChange={e=>setLot(e.target.value)}><option>ALL</option>{assessment.lots.map(l=><option key={l.id}>{l.id}</option>)}</select><select value={verdict} onChange={e=>setVerdict(e.target.value)}><option>ALL</option>{['QUALIFIED','MODULE A ANOMALY','EARLY DRIFT REJECT','FINAL REJECT'].map(x=><option key={x}>{x}</option>)}</select><span>{rows.length} RECORDS</span></div><div className="table-wrap"><table><thead><tr><th>COMPONENT ↕</th><th>LOT ↕</th><th>MODULE A ↕</th><th>MODULE B ↕</th><th>FINAL VERDICT ↕</th><th></th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td className="mono">{c.id}</td><td>{c.lot}</td><td><Verdict value={c.moduleA}/></td><td><Verdict value={c.moduleB}/></td><td><Verdict value={c.verdict}/></td><td><button className="row-action" onClick={()=>{pick(c.id);go('component')}}>INVESTIGATE →</button></td></tr>)}</tbody></table></div></section> }
function Reports({assessment,go}:{assessment:Assessment;go:(v:View)=>void}) { return <div className="reports"><section className="panel report-record"><span className="eyebrow">LATEST ASSESSMENT</span><h2>{assessment.id}</h2><p>{assessment.mission} · {assessment.scenario}</p><div><Verdict value="COMPLETE"/><span>{assessment.assessedAt}</span></div><button className="secondary" onClick={()=>go('overview')}>OPEN ASSESSMENT →</button></section><section className="empty-state"><span>▣</span><h2>RUN HISTORY</h2><p>Historical assessment records will appear here when the ABSS service layer is connected to a persistent mission repository.</p></section></div> }
